[package]
  cjc-version = "1.0.4"
  name = "zlibraryAPI4CJ"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  [package.package-configuration]

  
[dependencies]
  linderHttp = {path = "D:\\linderSeline\\projects\\Cangjie\\LinderHttp"}
  stdx_encode = {path = "D:\\linderSeline\\projects\\Cangjie\\standstdx\\stdx_standalone_encode"}
  stdx_encode_json = {path = "D:\\linderSeline\\projects\\Cangjie\\standstdx\\stdx_standalone_encode_json"}
  stdx_net = {path = "D:\\linderSeline\\projects\\Cangjie\\standstdx\\stdx_standalone_net"}
  stdx_serialization = {path = "D:\\linderSeline\\projects\\Cangjie\\standstdx\\stdx_standalone_serialization"}